org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.19.2
enabled_platforms=fabric,forge

architectury_version=6.6.92
parchment_version = 1.19.2:2022.11.27
forge_version=1.19.2-43.4.12

## Mod Properties
mod_id=scholar
mod_name=Scholar
mod_license=GNU GPLv3
mod_version=1.1.0
mod_group_id=io.github.mortuusars.scholar
mod_authors=mortuusars
mod_description=Book improvements: two-page view, colored books, QOL-features
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/scholar
mod_github = https://github.com/mortuusars/Scholar

## Dependency Versions
minecraft_version_range=[1.19.2,1.19.3)

forge_version_range=[43,)
loader_version_range=[43,)

fabric_loader_version=0.16.10
fabric_api_version=0.77.0+1.19.2
forge_config_api_version=4.2.11

mixinextras_version=0.4.1

# Mod Versions
jei_version=11.8.1.1034
